services:
  - type: web
    name: webble-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_API_KEY
        sync: false
    rootDir: backend
